apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ .Values.app }}
  labels:
    app: {{ .Values.app }}
    env: {{ .Values.env }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: {{ .Values.app }}
      env: {{ .Values.env }}

  template:
    metadata:
      labels:
        app: {{ .Values.app }}
        env: {{ .Values.env }}

    spec:
      containers:
        - name: {{ .Values.app }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.containerPort }}