apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-dev
  namespace: dev
spec:
  replicas: 6
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
        env: {{ .Values.env }}
        
    spec:
      containers:
        - name: my-app
          image: nginx:latest
          ports:
            - containerPort: 80
          env:
            - name: ENV
              value: {{ .Values.env }}